spring:
  datasource:
    url: jdbc:h2:file:./spring_test
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
server:
  port: 8081