spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
