CREATE TABLE car
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_name  VARCHAR(255),
    car_name    VARCHAR(255),
    description VARCHAR(255),
    driver_id   INT,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

CREATE TABLE driver
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    age        INT,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

ALTER TABLE car
    ADD CONSTRAINT FK_CAR_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);