<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home page</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
<div><a href="/swagger-ui/index.html?url=/v3/api-docs">Swagger</a></div>
<div><a href="/cars">Show cars</a></div>
<div><a href="/drivers">Show drivers</a></div>
<div><a href="/fillTestData">Fill test data</a></div>
</body>

</html>